# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
